### ISSUE TITLE
Bindings

### ISSUE THREAD

**Issue by marithpl** [maxnowack/homebridge-eq3ble#11]
[5/28/2017, 5:48:48 AM] ERROR LOADING PLUGIN homebridge-eq3ble:
[5/28/2017, 5:48:48 AM] Error: Cannot find module '../build/Release/binding.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-eq3ble/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Any advise?

**Comment by filiprozanski** [comment]
Hey @marithpl did you manage to fix it? I'm facing the same issue

**Comment by marithpl** [comment]
Yes, but to be honest I don’t know how. 
As I remember I try to update homebridge and all plugins. 

Pozdrawiam

**Comment by maxnowack** [comment]
Try installing as root and with `--unsafe-perm` flag

**Comment by filiprozanski** [comment]
Hi Max, thanks, did that and managed to install and connect to all my valves, unfortunately it's very unstable and rarely works :/
