### ISSUE TITLE
connection timeout

### ISSUE THREAD

**Issue by patafix18** [maxnowack/homebridge-eq3ble#14]
Hello,
I can't install the plugin. The installation interrupts with the message, that node-usb is missing. 
This is the error message:
node-pre-gyp ERR! Tried to download: https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindin   gs-v1.2.0-node-v48-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@6.10.0 (node-v48 ABI) (falling back    to source compile with node-gyp)

Homebridge starts to load the plugin but stops with the message:

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:601:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:126:16)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:382:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at /usr/local/lib/node_modules/homebridge-fritz/index.js:139:25
    at tryCatcher (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:668:14)

**Comment by patafix18** [comment]
With sudo killall homebridge i managed to start Homebridge sucessfully. But I think the plugin installation wasn't complete because node-usb couldn't be installed during the Installation process.
Furthermore I get an timed out: 


[2017-11-19 11:06:21] [Thermostat] cannot discover thermostat (00:1a:22:0b:1a:XX)
[2017-11-19 11:06:22] [Thermostat] Error: discovering thermostat timed out (00:1a:22:0b:1a:XX)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eq3ble/dist/thermostat.js:157:20)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by patafix18** [comment]
Okay I finally managed to install the plugin correctly with sudo and --unsafe perm. No error message occurs through the installation process. But I geht the following errors in HB:

[2017-11-19 19:23:01] [Thermostat] cannot discover thermostat (00:1a:22:0b:1a:XX)
[2017-11-19 19:23:01] [Thermostat] Error: discovering thermostat timed out (00:1a:22:0b:1a:XX)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eq3ble/dist/thermostat.js:157:20)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[2017-11-19 19:23:01] [Thermostat] connecting to thermostat (00:1a:22:0b:1a:XX)
[2017-11-19 19:23:01] [Thermostat] discovering thermostat (00:1a:22:0b:1a:XX)
 
Do you have an adivce for me? :)
