### ISSUE TITLE
What version does the plugin work with?

### ISSUE THREAD

**Issue by lantk** [maxnowack/homebridge-eq3ble#19]
- Rasbian (I have 2017-11-29)
- Node (8.9.4)
- Homebridge (0.4.38)
- Raspberry Pi Zero W

For mi not looking for a thermostat.

**Comment by sthonnard** [comment]
Hi,

I don't think this plugin will look for any thermostat. You need to add them in the config file manually:
 "accessories": [{
    "accessory": "EQ3-Thermostat",
    "name": "Thermostat",
    "address": "00:1a:22:07:48:77"
  }]

There is another plugin that seeks automatically for compatible bluetooth thermostats: homebridge-platform-eq3btsmart

**Comment by lantk** [comment]
> {
>   "bridge": {
>     "name": "Homebridge",
>     "username": "CC:22:3D:E3:CE:30",
>     "port": 51826,
>     "pin": "031-45-154"
>   },
> 
>   "accessories":
>  [
>   {
>     "accessory": "EQ3-Thermostat",
>     "name": "Living Room Thermostat",
>     "address": "00:1a:22:0b:b8:XX"
>   },
> ...

`[2018-3-1 20:07:47] [Living Room Thermostat] cannot discover thermostat (00:1a:22:0b:b8:XX)
[2018-3-1 20:07:47] [Living Room Thermostat] Error: discovering thermostat timed out (00:1a:22:0b:b8:XX)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eq3ble/dist/thermostat.js:157:20)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2018-3-1 20:07:47] [Living Room Thermostat] connecting to thermostat (00:1a:22:0b:b8:XX)
[2018-3-1 20:07:47] [Living Room Thermostat] discovering thermostat (00:1a:22:0b:b8:XX)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eq3ble/dist/thermostat.js:157:20)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
[2018-3-1 20:08:07] [Living Room Thermostat] connection to thermostat timed out (00:1a:22:0b:b8:XX)
[2018-3-1 20:08:07] [Living Room Thermostat] cannot discover thermostat (00:1a:22:0b:b8:XX)`

homebridge-platform-eq3btsmart
not working :(

`[2018-3-1 20:07:27] ====================
[2018-3-1 20:07:27] ERROR LOADING PLUGIN homebridge-platform-eq3btsmart:
[2018-3-1 20:07:27] Error: Cannot find module 'bluetooth-hci-socket'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-eq3btsmart/node_modules/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
[2018-3-1 20:07:27] ====================
`

I am asking about the versions, because I want it to work in the end :(

**Comment by sthonnard** [comment]
I don't know what version is required, I run on last. Can you try with the mac address in lower case?
00:1a:22:0b:b8:xx

**Comment by maxnowack** [comment]
It seems that bluetooth isn't working correctly with your (node) environment. I don't think, that this is an issue with this plugin …

**Comment by sthonnard** [comment]
You might try to run npm install bluetooth-hci-socket

**Comment by lantk** [comment]
I think it not compile on raspberry pi zero... and this is te problem.
