### ISSUE TITLE
1.3.3 version fails to start

### ISSUE THREAD

**Issue by sergejs** [maxnowack/homebridge-eq3ble#22]
Here is my config:
`{
    	"bridge": {
    	},
	"accessories": [{
    		"accessory": "EQ3-Thermostat",
    		"name": "Kitchen Radiator",
    		"address": "00:1a:22:0b:a8:34"
  	},
	{
    		"accessory": "EQ3-Thermostat",
    		"name": "Room Radiator",
    		"address": "00:1a:22:0b:ab:17"
 	},
	{
    		"accessory": "EQ3-Thermostat",
    		"name": "Badroom Radiator",
    		"address": "00:1a:22:0b:ac:29"
	}]
}`

After downgrading to 1.3.2 - everything works fine

error is: 

Loading 3 accessories...
/usr/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'EQ3-Thermostat' was not registered by any plugin.
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:286:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by xatrix78** [comment]
I have exactly the same problem. 1.3.2 works.

**Comment by mpalmer-mpi** [comment]
[2/11/2019, 3:42:17 PM] Loaded plugin: homebridge-eq3ble
[2/11/2019, 3:42:17 PM] Registering platform 'homebridge-platform-eq3ble.EQ3BLE'

Version 1.3.3 is somehow replaced with beta 2.0.0 (where it starts to be a platform and no longer being an accessory) when specifically installing 1.3.3

**Comment by derbroti** [comment]
[2/11/2019, 3:42:17 PM] Loaded plugin: homebridge-eq3ble
[2/11/2019, 3:42:17 PM] Registering platform 'homebridge-platform-eq3ble.EQ3BLE'

Version 1.3.3 is somehow replaced with beta 2.0.0 (where it starts to be a platform and no longer being an accessory) when specifically installing 1.3.3

**Comment by xatrix78** [comment]
So what can we do?

**Comment by derbroti** [comment]
@maxnowack needs to fix it. Otherwise, you can download the source of 1.3.3 and build the module yourself "npm run build" but that failed for me with lovely runtime errors related to either babel or something... but the whole callbackify thing did not work for me (with node 10.x and 11.x).

The errors thrown were:
`UnhandledPromiseRejectionWarning: TypeError: callback.apply is not a function`

**Comment by xatrix78** [comment]
I hope that @maxnowack do this. 1.3.2 has bugs.

**Comment by patafix18** [comment]
I also have the same issue with 1.3.3. Hopefully this will be fixed soon.

**Comment by maxnowack** [comment]
Should be fixed in `v1.3.4`. Sorry for inconvenience 😔

**Comment by derbroti** [comment]
Thanks! that works fine now!
